### ISSUE TITLE
48g的显卡提示CUDA out of memory

### ISSUE THREAD

**Issue by liudezhi12** [QwenLM/Qwen-Image#26]
我是48g的显卡，请问多少显存够用呀，我用的diffusers运行代码。
Tried to allocate 72.00 MiB. GPU 1 has a total capacity of 44.32 GiB of which 63.81 MiB is free. Process 1703173 has 44.24 GiB memory in use. Of the allocated memory 43.63 GiB is allocated by PyTorch, and 196.65 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
(base_lbm) root@tgys01-desktop:/data/lsc/IClight/qianw#

**Comment by 1091492188** [comment]
我测试需要65G显存

**Comment by pwatx** [comment]
怪不得我用24G显卡不行

**Comment by pizzapy3** [comment]
After 
pipe = pipe.to(device)

I added: 
pipe.vae.enable_tiling()

Mine still used over 50GB of VRAM but it got done

**Comment by Vincentdu-cn** [comment]
4卡4090也OOM咋回事。。。
`CUDA_VISIBLE_DEVICES=0,1,2,3 python demo.py`

**Comment by jucy5520** [comment]
add "pipe.enable_model_cpu_offload()" not "pipe = pipe.to(device)" can help

**Comment by wangwei1237** [comment]
> 4卡4090也OOM咋回事。。。 `CUDA_VISIBLE_DEVICES=0,1,2,3 python demo.py`

还不支持多卡推理，我们测试过程也发现这个问题了。文档中说是支持多GPU并行，但是并不支持多GPU推理。

https://github.com/QwenLM/Qwen-Image/issues/11

**Comment by babyta** [comment]
diffusers推理不如comfyui  pipe.enable_model_cpu_offload()这个会降低速度，但是显存确实会降低

**Comment by Young1993** [comment]
> 我测试需要65G显存

差不多，我这边单卡A100是61G

<img width="1052" height="350" alt="Image" src="https://github.com/user-attachments/assets/da09a387-46f1-4259-871f-af2e2664eb02" />
同时只能生成一张图，如果同时生成两张图，则显存溢出

**Comment by babyta** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by BXset** [comment]
48GB的显卡可以参考一下我们搞的这个推理工程：
https://github.com/KE-AI-ENG/FastDM/tree/main
在A100-40G，4090/4090D，RTX-8000上都是可以推理Qwen-Image的，OOM解决了，显存占20~24GB左右，就是把Text_encoder部分放到CPU上跑了，这部分也得占16G显存呢，也挺大的。

**Comment by babyta** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yangguoquan001** [comment]
推理的话48G够用的：
pipe = QwenImageEditPlusPipeline.from_pretrained("autodl-tmp/qwen-image-edit-2509", torch_dtype=torch.bfloat16,height=512, width=512, output_type='np', true_cfg_scale=4.0)
pipe.enable_model_cpu_offload()

**Comment by babyta** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Yourrunner** [comment]
> 4卡4090也OOM咋回事。。。 `CUDA_VISIBLE_DEVICES=0,1,2,3 python demo.py`

我也是4张4090部不起   一启动就OOM
