### ISSUE TITLE
运行出错RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by Mike-ihr** [QwenLM/Qwen-Image#85]
cuda version 11.8
pytorch version 2.5.1
A100 40GB
why encounter this promlem？
Traceback (most recent call last):
  File "/home/zjx/Qwen-Image/Qwen-Image-Edit.py", line 25, in <module>
    output = pipeline(**inputs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/diffusers/pipelines/qwenimage/pipeline_qwenimage_edit.py", line 676, in __call__
    prompt_embeds, prompt_embeds_mask = self.encode_prompt(
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/diffusers/pipelines/qwenimage/pipeline_qwenimage_edit.py", line 305, in encode_prompt
    prompt_embeds, prompt_embeds_mask = self._get_qwen_prompt_embeds(prompt, image, device)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/diffusers/pipelines/qwenimage/pipeline_qwenimage_edit.py", line 250, in _get_qwen_prompt_embeds
    outputs = self.text_encoder(
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/accelerate/hooks.py", line 175, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 1493, in forward
    outputs = self.model(
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/accelerate/hooks.py", line 175, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 1275, in forward
    image_embeds = self.get_image_features(pixel_values, image_grid_thw)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 1188, in get_image_features
    image_embeds = self.visual(pixel_values, grid_thw=image_grid_thw)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/accelerate/hooks.py", line 175, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 480, in forward
    hidden_states = blk(
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/accelerate/hooks.py", line 175, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 308, in forward
    hidden_states = hidden_states + self.attn(
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/accelerate/hooks.py", line 175, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 222, in forward
    self.qkv(hidden_states).reshape(seq_length, 3, self.num_heads, -1).permute(1, 0, 2, 3).unbind(0)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/accelerate/hooks.py", line 175, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/zjx/anaconda3/envs/Qwen-Image/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by ZetangForward** [comment]
Hi, plz check your installation environment and ensure it is consistent with the one specified in our documentation.

We have tested locally using the environment outlined in the README, and it works as expected. 

If you continue to encounter issues, kindly provide detailed information about your environment (package versions) so we can better assist you.
